#!/usr/bin/env bash
# Maintainer: YtRen <rytubuntulinux@gmail.com>
# Create Date: 2016-02-08
# Update: 2016-02-11
# Function: Adjust backlight and volume of Ubuntu Linux

# Adjust the backlight
function adjustBright()
{
	echo "password" | sudo -kS  cp /path/to/brightness .  
	sed -i "s/[0-9]/${1}/" brightness
	echo "password" | sudo -kS cp brightness /paht/to/directory/brightness/in/
	rm brightness
	echo 
}

# Increase the volume
function addVolume()
{
	amixer -q set Master $1%+ 
}

# Decrease the volume
function decVolume()
{
	amixer -q set Master $1%- 
}

# Display the HELP
function showHelp()
{
		echo -e "\e[1m================================= \e[1mHELP ===================================\e[0m"
		# Name
		echo -e "\e[1mNAME\e[0m\n   adjustvb - Adjust backlight and volume of Ubuntu Linux\n"

		# Synopsis
		echo -e "\e[1mSYNOPSIS\n\e[0m   adjustvb [\e[1m-b\e[0m \e[3m\e[4mnum\e[0m] [\e[1m-i\e[0m \e[3m\e[4mnum\e[0m] \
[\e[1m-d\e[0m \e[3m\e[4mnum\e[0m] [\e[1m-h\e[0m]\n"

		# Options
		echo -e "\e[1mOptions\e[0m\n\e[1m   -h\e[0m\n      See help\n\n\e[1m   -b\e[0m\e[3m \e[4mbrightLevel\e[0m\n      Adjust the backlight to \e[3m\e[4mbrightLevel\e[0m\
				 \n\n\e[1m   -i\e[0m\e[3m \e[4mnum\e[0m\n      Increase volume by \e[3m\e[4mnum\e[0m percent\n\n\e[1m   -d\e[0m \e[3m\e[4mnum\e[0m\n      Decrease volume by \e[3m\e[4mnum\e[0m percent"
		echo -e "\e[1m==========================================================================\e[0m"
	
}

haveChoice=false

# Parse the option
while getopts "hb:i:d:" opt
do
	case $opt in
		# Help
		h)
			haveChoice=true
			clear
			showHelp
			;;

		# Control the backlight
		b)
			haveChoice=true
			adjustBright $OPTARG
			;;

		# Increase the volume
		i)
			haveChoice=true
			addVolume $OPTARG
			;;

		# Decrease the volume
		d)
			haveChoice=true
			decVolume $OPTARG
			;;

		# Error
		?)
			haveChoice=true
			echo -e "Error: Invalid option.\nUse\n\n  \e[1m$ adjust.sh -h\e[0m \n\nfor more information."
			exit 1
			;;
	esac
done

# If no option(s)
if [ $haveChoice == false ]
then
	echo -e "Too few option.\nUse\n\n   \e[1m$ adjustvb -h\e[0m\n\nfor more information"
fi
